server:
  port: 8080

spring:
  auth:
    token: 445bf8df03f7e885c90fcbd21c692d7d3531b9f6b7ac2d35c4d1c63b1dd746bf

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:board;MODE=MYSQL;
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      data-locations: classpath:schema.sql
      mode: always
      platform: h2